apiVersion: v1
kind: Service
metadata:
  name: llmstack-gateway
  namespace: llmstack
  labels:
    app.kubernetes.io/name: llmstack
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: llmstack
    app.kubernetes.io/component: gateway
